# Generated by Django 5.1.3 on 2025-01-08 22:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('listing_name', models.CharField(max_length=255)),
                ('location_address', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('orgnization', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
