# Generated by Django 5.1.3 on 2024-12-11 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(null=True)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(max_length=5)),
                ('group_user', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
