# Generated by Django 5.1.3 on 2025-01-08 22:44

import django.contrib.gis.db.models.fields
import post_app.validators
import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='post_images/default_post_image.jpg', null=True, upload_to='post_images/')),
                ('title', models.CharField(null=True, validators=[post_app.validators.validate_title])),
                ('description', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default='San Diego, CA', null=True, srid=4326)),
                ('address', models.CharField(null=True, validators=[user_app.validators.validate_city_state_format])),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('is_public', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
