# Generated by Django 5.1.3 on 2024-12-15 03:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(null=True)),
                ('description', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default='92039', null=True, srid=4326)),
                ('address', models.CharField(null=True)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('is_public', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
