# Generated by Django 5.1.3 on 2024-12-12 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='address',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
