# Generated by Django 5.1.3 on 2024-12-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
