# Generated by Django 5.1.3 on 2024-12-16 22:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_userposts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='Union, MO', null=True, srid=4326),
        ),
    ]
