# Generated by Django 5.1.3 on 2024-12-17 03:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_alter_userposts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='San Diego, CA', null=True, srid=4326),
        ),
    ]
