# Generated by Django 5.1.3 on 2024-12-24 17:13

import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[user_app.validators.validate_password], verbose_name='Password'),
        ),
    ]
