# Generated by Django 5.1.3 on 2024-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Union, MO', max_length=100, null=True, verbose_name='Location Address'),
        ),
    ]
